version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    container_name: goofy_heyrovsky
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
    ports:
      - "8080:8080"
    labels:
      - "container_name=goofy_heyrovsky"
